-- MySQL Script generated by MySQL Workbench
-- Sun Dec  8 22:49:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Car_Dealership_Database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Car_Dealership_Database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Car_Dealership_Database` DEFAULT CHARACTER SET utf8 ;
USE `Car_Dealership_Database` ;

-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Customer` (
  `Customer_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `F_Name` VARCHAR(45) NULL,
  `M_Init` VARCHAR(45) NULL,
  `L_Name` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Phone` INT NULL,
  `Address` VARCHAR(45) NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Package`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Package` (
  `Package_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Time_Since_Purchase` INT NULL,
  PRIMARY KEY (`Package_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Time_Slot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Time_Slot` (
  `Time_Slot_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Start_Time` DATE NULL,
  `End_Time` DATE NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`Time_Slot_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Vehicle_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Vehicle_Type` (
  `Vehicle_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Make` VARCHAR(45) NULL,
  `Model` VARCHAR(45) NULL,
  `Year` DATE NULL,
  `Tire_Type` VARCHAR(45) NULL,
  `Engine_Type` VARCHAR(45) NULL,
  PRIMARY KEY (`Vehicle_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Car` (
  `Car_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Interior` VARCHAR(45) NULL,
  `Odometer` INT NULL,
  `Color` VARCHAR(45) NULL,
  `Vehicle_Type_Vehicle_ID` INT UNSIGNED NOT NULL,
  `License_Plate_State` VARCHAR(45) NULL COMMENT 'Derived Customer_Cars',
  `License_Plate` VARCHAR(45) NULL COMMENT 'Derived Customer_Cars',
  `Cost` DECIMAL(45) NULL COMMENT 'Derived Cars_In_Inventory',
  `Vehicle_Type_Vehicle_ID1` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Car_ID`, `Vehicle_Type_Vehicle_ID`, `Vehicle_Type_Vehicle_ID1`),
  INDEX `fk_Car_Vehicle_Type1_idx` (`Vehicle_Type_Vehicle_ID1` ASC) VISIBLE,
  CONSTRAINT `fk_Car_Vehicle_Type1`
    FOREIGN KEY (`Vehicle_Type_Vehicle_ID1`)
    REFERENCES `Car_Dealership_Database`.`Vehicle_Type` (`Vehicle_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Appointment` (
  `Appointment_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Drop_Off` DATE NULL,
  `Pick_Up` DATE NULL,
  `Appointment_Made_Date` DATE NULL,
  `Package_Package_ID` INT UNSIGNED NOT NULL,
  `Time_Slot_Time_Slot_ID` INT UNSIGNED NOT NULL,
  `Customer_Customer_ID` INT UNSIGNED NOT NULL,
  `Car_Car_ID` INT UNSIGNED NOT NULL,
  `Car_Vehicle_Type_Vehicle_ID` INT UNSIGNED NOT NULL,
  `Car_Vehicle_Type_Vehicle_ID1` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Appointment_ID`, `Time_Slot_Time_Slot_ID`, `Customer_Customer_ID`, `Car_Car_ID`, `Car_Vehicle_Type_Vehicle_ID`, `Car_Vehicle_Type_Vehicle_ID1`),
  INDEX `fk_Appointment_Package1_idx` (`Package_Package_ID` ASC) VISIBLE,
  INDEX `fk_Appointment_Time_Slot1_idx` (`Time_Slot_Time_Slot_ID` ASC) VISIBLE,
  INDEX `fk_Appointment_Customer1_idx` (`Customer_Customer_ID` ASC) VISIBLE,
  INDEX `fk_Appointment_Car1_idx` (`Car_Car_ID` ASC, `Car_Vehicle_Type_Vehicle_ID` ASC, `Car_Vehicle_Type_Vehicle_ID1` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_Package1`
    FOREIGN KEY (`Package_Package_ID`)
    REFERENCES `Car_Dealership_Database`.`Package` (`Package_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Time_Slot1`
    FOREIGN KEY (`Time_Slot_Time_Slot_ID`)
    REFERENCES `Car_Dealership_Database`.`Time_Slot` (`Time_Slot_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Customer1`
    FOREIGN KEY (`Customer_Customer_ID`)
    REFERENCES `Car_Dealership_Database`.`Customer` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Car1`
    FOREIGN KEY (`Car_Car_ID` , `Car_Vehicle_Type_Vehicle_ID` , `Car_Vehicle_Type_Vehicle_ID1`)
    REFERENCES `Car_Dealership_Database`.`Car` (`Car_ID` , `Vehicle_Type_Vehicle_ID` , `Vehicle_Type_Vehicle_ID1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Task` (
  `Task_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Estd_Time` TIME NULL,
  `Est_Labor_Cost` DOUBLE NULL,
  PRIMARY KEY (`Task_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Part`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Part` (
  `Part_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cost_Of_Part` DECIMAL(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Task_Task_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Part_ID`, `Task_Task_ID`),
  INDEX `fk_Part_Task1_idx` (`Task_Task_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Part_Task1`
    FOREIGN KEY (`Task_Task_ID`)
    REFERENCES `Car_Dealership_Database`.`Task` (`Task_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Purchase` (
  `Purchase_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Date_Of_Purchase` DATE NULL,
  `Car_Car_ID` INT UNSIGNED NOT NULL,
  `Car_Vehicle_Type_Vehicle_ID` INT UNSIGNED NOT NULL,
  `Car_Vehicle_Type_Vehicle_ID1` INT UNSIGNED NOT NULL,
  `Sale_Price` DECIMAL(45) NULL COMMENT 'Was_Bought Relationship Value',
  PRIMARY KEY (`Purchase_ID`),
  INDEX `fk_Purchase_Car1_idx` (`Car_Car_ID` ASC, `Car_Vehicle_Type_Vehicle_ID` ASC, `Car_Vehicle_Type_Vehicle_ID1` ASC) VISIBLE,
  CONSTRAINT `fk_Purchase_Car1`
    FOREIGN KEY (`Car_Car_ID` , `Car_Vehicle_Type_Vehicle_ID` , `Car_Vehicle_Type_Vehicle_ID1`)
    REFERENCES `Car_Dealership_Database`.`Car` (`Car_ID` , `Vehicle_Type_Vehicle_ID` , `Vehicle_Type_Vehicle_ID1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Used_In`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Used_In` (
  `Vehicle_Type_Vehicle_ID` INT UNSIGNED NOT NULL,
  `Part_Part_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Vehicle_Type_Vehicle_ID`, `Part_Part_ID`),
  INDEX `fk_Vehicle_Type_has_Part_Part1_idx` (`Part_Part_ID` ASC) VISIBLE,
  INDEX `fk_Vehicle_Type_has_Part_Vehicle_Type_idx` (`Vehicle_Type_Vehicle_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Vehicle_Type_has_Part_Vehicle_Type`
    FOREIGN KEY (`Vehicle_Type_Vehicle_ID`)
    REFERENCES `Car_Dealership_Database`.`Vehicle_Type` (`Vehicle_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehicle_Type_has_Part_Part1`
    FOREIGN KEY (`Part_Part_ID`)
    REFERENCES `Car_Dealership_Database`.`Part` (`Part_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Recommends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Recommends` (
  `Package_Package_ID` INT UNSIGNED NOT NULL,
  `Task_Task_ID` INT UNSIGNED NOT NULL,
  `Is_Mandatory` TINYINT NULL,
  PRIMARY KEY (`Package_Package_ID`, `Task_Task_ID`),
  INDEX `fk_Package_has_Task_Task1_idx` (`Task_Task_ID` ASC) VISIBLE,
  INDEX `fk_Package_has_Task_Package1_idx` (`Package_Package_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Package_has_Task_Package1`
    FOREIGN KEY (`Package_Package_ID`)
    REFERENCES `Car_Dealership_Database`.`Package` (`Package_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Package_has_Task_Task1`
    FOREIGN KEY (`Task_Task_ID`)
    REFERENCES `Car_Dealership_Database`.`Task` (`Task_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Was_Replaced`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Was_Replaced` (
  `Appointment_Appointment_ID` INT UNSIGNED NOT NULL,
  `Part_Part_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Appointment_Appointment_ID`, `Part_Part_ID`),
  INDEX `fk_Appointment_has_Part_Part1_idx` (`Part_Part_ID` ASC) VISIBLE,
  INDEX `fk_Appointment_has_Part_Appointment1_idx` (`Appointment_Appointment_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_has_Part_Appointment1`
    FOREIGN KEY (`Appointment_Appointment_ID`)
    REFERENCES `Car_Dealership_Database`.`Appointment` (`Appointment_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_has_Part_Part1`
    FOREIGN KEY (`Part_Part_ID`)
    REFERENCES `Car_Dealership_Database`.`Part` (`Part_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Additionally_Scheduled`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Additionally_Scheduled` (
  `Appointment_Appointment_ID` INT UNSIGNED NOT NULL,
  `Task_Task_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Appointment_Appointment_ID`, `Task_Task_ID`),
  INDEX `fk_Appointment_has_Task_Task1_idx` (`Task_Task_ID` ASC) VISIBLE,
  INDEX `fk_Appointment_has_Task_Appointment1_idx` (`Appointment_Appointment_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_has_Task_Appointment1`
    FOREIGN KEY (`Appointment_Appointment_ID`)
    REFERENCES `Car_Dealership_Database`.`Appointment` (`Appointment_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_has_Task_Task1`
    FOREIGN KEY (`Task_Task_ID`)
    REFERENCES `Car_Dealership_Database`.`Task` (`Task_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Was_Performed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Was_Performed` (
  `Appointment_Appointment_ID` INT UNSIGNED NOT NULL,
  `Task_Task_ID` INT UNSIGNED NOT NULL,
  `Labor_Cost` DECIMAL(45) NULL,
  `Time` TIME NULL,
  PRIMARY KEY (`Appointment_Appointment_ID`, `Task_Task_ID`),
  INDEX `fk_Appointment_has_Task1_Task1_idx` (`Task_Task_ID` ASC) VISIBLE,
  INDEX `fk_Appointment_has_Task1_Appointment1_idx` (`Appointment_Appointment_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_has_Task1_Appointment1`
    FOREIGN KEY (`Appointment_Appointment_ID`)
    REFERENCES `Car_Dealership_Database`.`Appointment` (`Appointment_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_has_Task1_Task1`
    FOREIGN KEY (`Task_Task_ID`)
    REFERENCES `Car_Dealership_Database`.`Task` (`Task_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Made Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Made Purchase` (
  `Customer_Customer_ID` INT UNSIGNED NOT NULL,
  `Purchase_Purchase_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Customer_Customer_ID`, `Purchase_Purchase_ID`),
  INDEX `fk_Customer_has_Purchase_Purchase1_idx` (`Purchase_Purchase_ID` ASC) VISIBLE,
  INDEX `fk_Customer_has_Purchase_Customer1_idx` (`Customer_Customer_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_has_Purchase_Customer1`
    FOREIGN KEY (`Customer_Customer_ID`)
    REFERENCES `Car_Dealership_Database`.`Customer` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_Purchase_Purchase1`
    FOREIGN KEY (`Purchase_Purchase_ID`)
    REFERENCES `Car_Dealership_Database`.`Purchase` (`Purchase_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Owns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Owns` (
  `Customer_Customer_ID` INT UNSIGNED NOT NULL,
  `Car_Car_ID` INT UNSIGNED NOT NULL,
  `Car_Vehicle_Type_Vehicle_ID` INT UNSIGNED NOT NULL,
  `Car_Vehicle_Type_Vehicle_ID1` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Customer_Customer_ID`, `Car_Car_ID`, `Car_Vehicle_Type_Vehicle_ID`, `Car_Vehicle_Type_Vehicle_ID1`),
  INDEX `fk_Customer_has_Car_Car1_idx` (`Car_Car_ID` ASC, `Car_Vehicle_Type_Vehicle_ID` ASC, `Car_Vehicle_Type_Vehicle_ID1` ASC) VISIBLE,
  INDEX `fk_Customer_has_Car_Customer1_idx` (`Customer_Customer_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_has_Car_Customer1`
    FOREIGN KEY (`Customer_Customer_ID`)
    REFERENCES `Car_Dealership_Database`.`Customer` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_Car_Car1`
    FOREIGN KEY (`Car_Car_ID` , `Car_Vehicle_Type_Vehicle_ID` , `Car_Vehicle_Type_Vehicle_ID1`)
    REFERENCES `Car_Dealership_Database`.`Car` (`Car_ID` , `Vehicle_Type_Vehicle_ID` , `Vehicle_Type_Vehicle_ID1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Car_Dealership_Database`.`Failure_Requires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Car_Dealership_Database`.`Failure_Requires` (
  `Task_Task_ID1` INT UNSIGNED NOT NULL,
  `Task_Task_ID2` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Task_Task_ID1`, `Task_Task_ID2`),
  INDEX `fk_Task_has_Task_Task2_idx` (`Task_Task_ID2` ASC) VISIBLE,
  INDEX `fk_Task_has_Task_Task1_idx` (`Task_Task_ID1` ASC) VISIBLE,
  CONSTRAINT `fk_Task_has_Task_Task1`
    FOREIGN KEY (`Task_Task_ID1`)
    REFERENCES `Car_Dealership_Database`.`Task` (`Task_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_has_Task_Task2`
    FOREIGN KEY (`Task_Task_ID2`)
    REFERENCES `Car_Dealership_Database`.`Task` (`Task_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
